### ISSUE TITLE
Submitting the same survey twice results in an error

### ISSUE THREAD

**Issue by stavv** [SurveyMonkey/surveymonkey-android-sdk#11]
Desired behaviour:
As long as the user didn't answer the survey or submitted it without any answers (zero responses) I will keep nudging him to take the survey.

What actually happens:
Submitting the survey for the second time with answers results in error 8 in the calling activity.
(8 - Domain: SurveyMonkeySDK_ServerError Code: 8 SMDescription: The user canceled out of the survey.)

Steps to reproduce the problem:
Display the survey, submit without answers. Get RESULT_OK and 0 responses.
Display the survey again, submit with few answers. Get RESULT_CANCELED with no "smRespondent" in the intent.

Work around:
Kill the app from the task manager and show the survey again. Now submit with answers and it works.

Hope I was clear enough in my description.

Thanks in advance,
Stav

**Comment by stavv** [comment]
Worked around it by instantiating the SurveyMonkey SDK every time I need to show the survey right before calling:
`sdkInstance.startSMFeedbackActivityForResult(this, REQ_SURVEY, surveyHash);`

**Comment by benleiken** [comment]
@stavv Thanks for opening the issue -- this is a bug. Investigating now, more soon.
