### ISSUE TITLE
How to get Survey Lists

### ISSUE THREAD

**Issue by thesoal** [SurveyMonkey/surveymonkey-android-sdk#12]
I have some question regarding MonkeySurvey android sdk.

1)  I want to show multiple survey in my android application using MonkeySurvey android SDK. If user complete a survey,  i want to show other survey after some time. Is it posible to show different-different survey at runtime without chaging in application code?

2) How can we get a perticular user has complete his survey or not?

3) How can we get list of  my all survey and status of a servey, wheater it is completed or not for a user in my android application using  MonkeySurvey android SDK?

**Comment by benleiken** [comment]
Hey @thesoal,

All of the use cases you describe require a GOLD plan or higher.

1. You would have to set up all of the different survey hashes ahead of time, but you could certainly use the respondent data returned in `onActivityResult() ` to detect a completed survey and then track that information in your app and use it to to decide which survey to display next. But the key thing is that you have to set up all of the surveys ahead of time.

2. The only way to get this is by having a GOLD plan or higher and checking the respondent returned to `onActivityResult` to make sure he/she completed the survey successfully.

3. We don't support this functionality at this time. Future releases might include this feature!

Let me know if I can clarify anything!
