### ISSUE TITLE
 Application Get Crash

### ISSUE THREAD

**Issue by dineshswaas** [SurveyMonkey/surveymonkey-android-sdk#14]
The application  gets Crash when submitting the survey Without internet Connection .
(Mobile Brand - MI, Moble Model - Redmi 3S)

**Comment by benleiken** [comment]
@dineshswaas I'm unable to reproduce this issue, as the current version of the SDK displays a "you're offline" overlay when internet connection is lost and prevents the survey from being submitted. If you can provide further reproduction steps, please reopen this.
