### ISSUE TITLE
Unwanted question after end of survey freezes the app

### ISSUE THREAD

**Issue by ber4444** [SurveyMonkey/surveymonkey-android-sdk#16]
![screenshot_1471646454](https://cloud.githubusercontent.com/assets/205867/17826491/212dc4aa-6626-11e6-9e3b-35e94a339ef4.png)

I'm sometimes getting this dialog from the android SDK out of the blue after completing the survey. The buttons in this dialog do not work and just freeze my app. Any way of getting rid of this spam?

**Comment by ber4444** [comment]
I tried to disable it like this (unsuccessfully!!!):

```
      sdkInstance.onStart(activity, REQUEST_CODE_SURVEY, hash,
                          String.format(activity.getResources().getString(
                             com.surveymonkey.surveymonkeyandroidsdk.R.string.sm_prompt_title_text),
                                        res.getString(R.string.app_name)),
                       res.getString(com.surveymonkey.surveymonkeyandroidsdk.R.string.sm_prompt_message_text),
                          0L, 0L, 0L, null);
```

**Comment by benleiken** [comment]
@ber4444 If you just want to display the survey once, you shouldn't be using `.onStart()` as this method triggers the timed intercept, you should use `.startSMFeedbackActivityForResult(this, [SAMPLE_REQUEST_CODE], [SAMPLE_SURVEY_HASH]); `as outlined in the documentation.

Hope this helps you!

**Comment by ber4444** [comment]
Bad API design. SurveyFragmentActivity should have a method that disables the timed intercept. Now I need to migrate the whole logic out of the dedicated FragmentActivity?

**Comment by benleiken** [comment]
I'm not sure what your use case is, but the scheduled intercept is meant for [continuously gathering in-app feedback from your users](https://github.com/SurveyMonkey/surveymonkey-android-sdk#random-polling). If your use case differs, then you can use startSMFeedBackActivity or newSMFeedbackFragmentInstance (if you prefer Fragments) to display a survey according to your needs.

If our documentation can be improved to make any of this clearer, please feel free to suggest edits.

Thanks!

**Comment by ber4444** [comment]
I was looking at https://github.com/SurveyMonkey/surveymonkey-android-sdk/blob/master/SimpleSurvey/app/src/main/java/com/surveymonkey/simplesurvey/SimpleActivity.java
takeSurvey(View view) and takeSurveyFragment(View view) has the exact same documentation so it suggests they are two ways to do the same thing - but it seems one of them has this scheduling behavior under the hoods and the other doesn't, which is surprising\; and the documentation elsewhere does not make things clear either; I appreciate your quick reply here at least.
