### ISSUE TITLE
Remove allowBackup declaration

### ISSUE THREAD

**Issue by Vandalko** [SurveyMonkey/surveymonkey-android-sdk#17]
Library explicitly declares `android:allowBackup` which, in fact, should be decided by application, not library. Also, it requires additional changes in application manifest to suppress this flags during manifests merge process.

```
    <application android:allowBackup="true" >
        <activity
            android:name="com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity"
            android:screenOrientation="locked"
            android:windowSoftInputMode="adjustResize" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
    </application>
```

**Comment by Vandalko** [comment]
One may suggest to use `tools:replace="android:allowBackup"` in target application, but it looks like it's not yet possible due to old bug still present in at least `2.1.3` plugin:
https://code.google.com/p/android/issues/detail?id=70073

**Comment by ibendayan** [comment]
Any news?

**Comment by ayeung** [comment]
Removed the 'android:allowBackup' flag, and will be a part of the next release.
