### ISSUE TITLE
Do not hijack default uncaught exception handler

### ISSUE THREAD

**Issue by Vandalko** [SurveyMonkey/surveymonkey-android-sdk#18]
`SMFeedbackFragment` has very interesting code:

``` java

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
       //....
        Thread.setDefaultUncaughtExceptionHandler(new SMExceptionHandler(this));
        //...

    }

    private void handleError(SMError e) {
        try {
            ((SMFeedbackFragmentListener) getActivity()).onFetchRespondentFailure(e);
        }
        catch (ClassCastException cce) {
            Log.d(SMConstants.DEBUG_TAG, "SMFeedbackFragmentListener has not been implemented");
            if (e.getErrorCode() == SMError.ErrorType.ERROR_CODE_COLLECTOR_CLOSED.getValue()) {
                showSurveyClosedOverlay();
            }
            else {
                showEndOfSurveyOverlay();
            }
        }
    }

    protected class SMExceptionHandler implements
            java.lang.Thread.UncaughtExceptionHandler {

        public SMExceptionHandler(Fragment context) {
        }

        public void uncaughtException(Thread thread, Throwable exception) {
            SMError cause = (SMError) exception.getCause();
            handleError(cause);
        }
    }
```

And I'm not even mad - I see that you want to prevent any unexpected errors, but in reality, it's not your job :) There are libs like Crashlytics or ACRA which are responsible from crash handling. At the very end - it's an application responsibility to decide what to do with unexpected errors.

But there are a few very critical errors here:
- `SMExceptionHandler` does not propagate exceptions to underlying handler, practically destroying all exception handling mechanism in whole app
- `SMExceptionHandler` captures outer context in form of `Fragment` - it would be eventually detached from `Activity`, but the `Fragment` instance would still be present due to static reference in main thread

**Comment by ayeung** [comment]
@Vandalko Thanks for the feedback.  I've removed the SMExceptionHandler, so hopefully this will no longer conflict with other crash management systems.
