### ISSUE TITLE
Survey submit returns error but result is available on web site

### ISSUE THREAD

**Issue by Vandalko** [SurveyMonkey/surveymonkey-android-sdk#19]
Submitting a survey response returns error (basic free plan):

```
Domain: SurveyMonkeySDK_ServerError Code: 7 SMDescription: Response limit exceeded for your plan. Upgrade to access more responses through the SDK.
```

But on the website, under Analyze Results tab, I can see submitted response.

**Comment by ashokgujju** [comment]
Same issue.. I'm getting the following message in android (SELECT plan user)
` D/SM_SDK_DEBUG: Domain: SurveyMonkeySDK_ServerError Code: 10 SMDescription: Internal server error.
11-07 17:05:28.393 21764-21764/com.surveymonkey.simplesurvey D/SM-ERROR: Domain: SurveyMonkeySDK_ServerError Code: 10 SMDescription: Internal server error.`

**Comment by ashokgujju** [comment]
Same issue.. Never got RESULT_OK in onActivityResult() but result is available on web. (SELECT Plan user)

**Comment by benleiken** [comment]
@Vandalko @ashokgujju this is a known issue -- the SDK is trying to tell you to upgrade (since the response parsing feature is only available to users with GOLD plans and higher)

There will be improvements to our handling of this case in the next release!
