### ISSUE TITLE
Class cast error

### ISSUE THREAD

**Issue by gondzo** [SurveyMonkey/surveymonkey-android-sdk#20]
When submitting a survey twice with that action being disabled for a survey, a ClassCastException is thrown

com.surveymonkey.surveymonkeyandroidsdk.loaders.GetRespondentTaskLoader cannot be cast to 
com.surveymonkey.surveymonkeyandroidsdk.loaders.GetRespondentTokenTaskLoader

at SMFeedbackFragment.getToken()

This is a major issue as the entire app crashes without any error handling

**Comment by iChicory** [comment]
It looks like because there used wrong hardcoded value 2, instead of RESPONDENT_TOKEN_LOADER_KEY that is constant 1
`GetRespondentTokenTaskLoader loader = (GetRespondentTokenTaskLoader) getActivity().getSupportLoaderManager().getLoader(2);
        `

**Comment by ayeung** [comment]
Duplicate of https://github.com/SurveyMonkey/surveymonkey-android-sdk/issues/38
