### ISSUE TITLE
Android Sdk server response error

### ISSUE THREAD

**Issue by susanSanjhya** [SurveyMonkey/surveymonkey-android-sdk#21]

**Comment by susanSanjhya** [comment]
The SDK was working fine before but now the sdk server response is returning below error description.
Domain: SurveyMonkeySDK_ServerError Code: 10 SMDescription: Internal server error.

**Comment by benleiken** [comment]
@susanSanjhya thanks for bringing this to our attention. We are working on a fix and will have an update as soon as possible.

**Comment by benleiken** [comment]
@susanSanjhya the issue has been fixed. Let me know if any other issues arise!

**Comment by susanSanjhya** [comment]
@benleiken Thanks a lot. It's working fine now. Thank you for your quick support.
