### ISSUE TITLE
SSLHandshakeException: Connection closed by peer

### ISSUE THREAD

**Issue by azfarsiddiqui** [SurveyMonkey/surveymonkey-android-sdk#22]
Hi Chaps,

So I am pretty new to SurveyMonkey SDK and I am getting this exception when I fetch a survey using:

**mSurveyMonkeySdk.startSMFeedbackActivityForResult(getActivity(), 0, "xxxxx");**

The exception occurs inside **RetrieveSPageTask** class's **doInBackground** method. The URL that it tries to fetch is like https://www.surveymonkey.com/r/xxxxxx. I cant also fetch this URL using a REST client. I am behind a proxy though due to organization requirements. When I route the traffic through my 4g network, there are no issues. 

The issue that I cant get my head around is even on the organization network, the URL https://www.surveymonkey.com/r/xxxxxx opens without any issues on my browser. But for some reason, the request through my rest client fails. 

Two questions:
1- Is there any workaround so that the SDK works on all sorts of networks?
2- How can I test the API call using a REST client?

Thanks guys!

**Comment by benleiken** [comment]
@azfarsiddiqui can you post the full stack trace please? This is definitely related to the proxy you're using, but we'll see if we can find a fix in our next release

**Comment by azfarsiddiqui** [comment]
@benleiken , there is no crash. This exception is caught in RetrieveSPageTask->doInBackground catch block and the survey initialization fails silently. On my other question, can I test the API call to get the survey using a REST client?

**Comment by benleiken** [comment]
Definitely -- it's just a GET request to https://www.surveymonkey.com/r/xxxxxx or whatever your Survey Hash is -- though it's not a JSON API, so the response won't be very useful.

**Comment by azfarsiddiqui** [comment]
I tried that and it didnt work, probably because of my network rules. I thought there might be some auth headers required or stuff. Anyway, thanks.

**Comment by azfarsiddiqui** [comment]
@benleiken , does the SDK have certificate pinning?

**Comment by azfarsiddiqui** [comment]
Change a firewall rule which was blocking Survey Monkey API. All is good now. Closing the ticket.
