### ISSUE TITLE
Unable to increase the font size of Survey Page title

### ISSUE THREAD

**Issue by mangarajmadhu** [SurveyMonkey/surveymonkey-android-sdk#23]
I am unable to change the font size of page title. Though I am increasing to the maximum possible size provided by survey monkey, it is not reflecting on my phone.

Survey Monkey support team says, it could be an issue with the Mobile sdk.
Please have a look into the issue. 

We are an enterprise account holder of SurveyMonkey. Please revert me back ASAP

Thank you.

**Comment by benleiken** [comment]
@mangarajmadhu our responsive mobile layout doesn't currently support increased page title font sizes. This is not an issue with the SDK. I will open a ticket with that team and see why we prevent changing the font size on mobile.

You'll need to contact customer support for any billing changes/inquiries: https://help.surveymonkey.com/articles/en_US/kb/What-is-your-phone-number
