### ISSUE TITLE
Empty item for selection in Dropdown

### ISSUE THREAD

**Issue by mangarajmadhu** [SurveyMonkey/surveymonkey-android-sdk#24]
![screenshot_20161130-112229 1](https://cloud.githubusercontent.com/assets/23693304/20741309/72197cd2-b6ef-11e6-937e-396fe55176e9.png)

Why this empty option comes for the dropdown?

**Comment by benleiken** [comment]
To give the user the option to not answer the question. Please address further layout questions to our Customer Support team: https://help.surveymonkey.com/articles/en_US/kb/What-is-your-phone-number
