### ISSUE TITLE
Survey not loading in Android 7.0 (API 24)

### ISSUE THREAD

**Issue by biohzrdmx** [SurveyMonkey/surveymonkey-android-sdk#28]
Hi, we're having an issue with the survey, it is not loading on the latest Android version (tested on the emulator and a couple real phones). 

The 'Loading...' dialog appears, but after a few seconds the spinner stops and the app freezes; there are no exceptions reported on the logcat, only the following output after invoking the survey with the `startSMFeedbackActivityForResult` method:

	03-06 18:37:22.377 11776-11776/com.test.app D/debug: 9
	03-06 18:37:23.446 669-680/system_process I/ActivityManager: START u0 {cmp=com.test.app/com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity (has extras)} from uid 10063 on display 0
	03-06 18:37:23.814 11776-11776/com.test.app W/System: ClassLoader referenced unknown path: /system/app/webview/lib/x86
	03-06 18:37:23.842 11776-11776/com.test.app I/WebViewFactory: Loading com.android.webview version 51.0.2704.91 (code 275509110)
	03-06 18:37:23.942 11776-11776/com.test.app I/cr_LibraryLoader: Time to load native libraries: 19 ms (timestamps 5976-5995)
	03-06 18:37:23.942 11776-11776/com.test.app I/cr_LibraryLoader: Expected native library version number "51.0.2704.91", actual native library version number "51.0.2704.91"
	03-06 18:37:24.022 11776-11776/com.test.app V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {7139131}
	03-06 18:37:24.023 11776-11776/com.test.app I/cr_LibraryLoader: Expected native library version number "51.0.2704.91", actual native library version number "51.0.2704.91"
	03-06 18:37:24.025 11776-11776/com.test.app I/chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
	03-06 18:37:24.090 11776-11776/com.test.app I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
	03-06 18:37:24.130 11776-11776/com.test.app E/ApkAssets: Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
	03-06 18:37:24.131 11776-11776/com.test.app E/ApkAssets: Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
	03-06 18:37:24.485 11776-12384/com.test.app W/cr_media: Requires BLUETOOTH permission
	03-06 18:37:24.540 11776-11776/com.test.app I/cr_DRP: No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
	03-06 18:37:24.699 11776-11776/com.test.app D/cr_Ime: [InputMethodManagerWrapper.java:30] Constructor
	03-06 18:37:24.781 11776-11776/com.test.app W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
	03-06 18:37:24.794 11776-11776/com.test.app D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
	03-06 18:37:24.970 11776-11776/com.test.app I/cr_Ime: ImeThread is not enabled.
	03-06 18:37:25.062 11776-12401/com.test.app E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
	03-06 18:37:25.256 11776-12401/com.test.app W/AudioCapabilities: Unsupported mime audio/x-pcm
	03-06 18:37:25.351 11776-12401/com.test.app I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
	                                                                           
	                                                                           [ 03-06 18:37:25.386 11776:12401 D/         ]
	                                                                           HostConnection::get() New Host Connection established 0xd68bdf10, tid 12401
	03-06 18:37:26.205 11776-11776/com.test.app I/Choreographer: Skipped 56 frames!  The application may be doing too much work on its main thread.
	03-06 18:37:27.692 11776-11776/com.test.app I/Choreographer: Skipped 88 frames!  The application may be doing too much work on its main thread.
	03-06 18:37:27.888 669-692/system_process I/ActivityManager: Displayed com.test.app/com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity: +4s391ms
	03-06 18:37:28.220 11776-11776/com.test.app W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 11776
	03-06 18:37:28.222 11776-11776/com.test.app D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
	03-06 18:37:28.238 11776-11776/com.test.app I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
	03-06 18:37:28.499 669-681/system_process I/WindowManager: Destroying surface Surface(name=com.test.app/com.test.app.MenuActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3017 com.android.server.wm.WindowManagerService.relayoutWindow:2897 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 
	03-06 18:37:31.676 11776-11782/com.test.app W/art: Suspending all threads took: 47.498ms
	03-06 18:37:32.743 420-438/? W/AudioFlinger: write blocked for 10356 msecs, 8 delayed writes, thread 0xf3903d40
	03-06 18:37:33.469 669-683/system_process W/ActivityManager: Launch timeout has expired, giving up wake lock!
	03-06 18:37:43.536 669-683/system_process W/ActivityManager: Activity stop timeout for ActivityRecord{9d9aae0 u0 com.test.app/.MenuActivity t8}

Regards.

**Comment by Vandalko** [comment]
> The 'Loading...' dialog appears, but after a few seconds the spinner stops and the app freezes;

I've got somewhat similar behavior on Android 6.
The 'Loading..' dialog animation where not smooth meaning there is extensive work in UI thread going on and then even when survey loaded, dialog did not disappear.

**Comment by ayeung** [comment]
@biohzrdmx Which device did you use to test this?  I tried on Android 7.1.1 on an Essential phone with the demo app and it seemed to work fine.  I also tried against Android 8.0 on a google pixel and that works as well.
