### ISSUE TITLE
Only android.support.v4 version of Fragment API

### ISSUE THREAD

**Issue by ktalanda** [SurveyMonkey/surveymonkey-android-sdk#29]
`android.support.v4.app.Fragment` which is super class for `SMFeedbackFragment` is not compatible with `android.app.Fragment`, so it cannot be used in systems not using `support` library for Fragments.

**Comment by benleiken** [comment]
@ktalanda we're (finally) taking a look at this. We want the SDK to support as many Android SDK versions as possible (pre API 11 even) -- we assumed having our SMFeedbackFragment inherit from the support fragment would allow us to accomplish that. It seems that switching to android.app.Fragment would prevent us from supporting pre-API 11 apps -- if that's not the case, correct our assumption!
