### ISSUE TITLE
Android Sdk response: Internal Server Error

### ISSUE THREAD

**Issue by susanSanjhya** [SurveyMonkey/surveymonkey-android-sdk#30]
The SDK was working fine till thursday but now the sdk server response is returning below mentioned error description.

Domain: SurveyMonkeySDK_ServerError Code: 10 SMDescription: Internal server error.

As it has been integrated in live app, we need an immediate solution.

thanks

**Comment by Vandalko** [comment]
Same problem here:
```
SM_SDK_DEBUG: Domain: SurveyMonkeySDK_ServerError Code: 10 SMDescription: Internal server error.
```

**Comment by benleiken** [comment]
We are aware of this issue and are actively working on a fix. This should be resolved later today. Will update here.

**Comment by benleiken** [comment]
@Vandalko @susanSanjhya this issue has been resolved. Thanks for your patience!
