### ISSUE TITLE
SDK resonse failure

### ISSUE THREAD

**Issue by finesushil** [SurveyMonkey/surveymonkey-android-sdk#32]
It has been noticed that there is a frequent failure in reporting the response. While checking in surveymonkey, all the response of the user us recorded but the SDK fails to provide success response to our app.

It creates difference in report generated from two different platforms. As we pay users for every successful completion, when survey monkey does not send us successful response, users are deprived of their benefit which is creating dissatisfaction among our users.

We are the platinum user of Survey monkey. Username: Chekea

Please look into it asap.

thanks

**Comment by benleiken** [comment]
@finesushil what error code(s) are you seeing? There are several cases where it probably doesn't make sense to assume that a response wasn't recorded. 


`ERROR_CODE_TOKEN    1    Could not retrieve your respondent. Be sure you're using an SDK Collector.
ERROR_CODE_BAD_CONNECTION    2    There was an error connecting to the server.
ERROR_CODE_RESPONSE_PARSE_FAILED    3    There was an error parsing the response from the server.
ERROR_CODE_COLLECTOR_CLOSED    4    The collector for this survey has been closed.
ERROR_CODE_RETRIEVING_RESPONSE    5    There was a problem retrieving the user's response to this survey.
ERROR_CODE_SURVEY_DELETED    6    This survey has been deleted.
ERROR_CODE_RESPONSE_LIMIT_HIT    7    Response limit exceeded for your plan. Upgrade to access more responses through the SDK.
ERROR_CODE_RESPONDENT_EXITED_SURVEY    8    The user canceled out of the survey.
ERROR_CODE_NONEXISTENT_LINK    9    Custom link no longer exists.
ERROR_CODE_INTERNAL_SERVER_ERROR    10    Internal server error.`

**Comment by finesushil** [comment]
@benleiken 
While we test, none of this ever happens except for Internal Server error sometimes. This happens with live app and we havent been able to trace the error code.

Which of the above errors records successful in survey monkey but might not give success by SDK.
So that we can handle those errors.

Looking forward to your response

thanks 
sushil

**Comment by benleiken** [comment]
@finesushil error codes 1,2,3,5,7 and 10 could all record successful survey responses in our DB -- we'd recommend treating all of those as successful submissions.

I'd recommend only assuming an incomplete/unsubmitted response when you get a 9, 8, or 6 back from the SDK. Hope that's helpful -- I will update our documentation to better clarify how the SDK interacts with our servers.

**Comment by susanSanjhya** [comment]
@benleiken 
ERROR_CODE_BAD_CONNECTION 2 There was an error connecting to the server.
ERROR_CODE_INTERNAL_SERVER_ERROR 10 Internal server error.
--> How can the survey be posted in your database in the above cases? Please clarify
thanks

**Comment by benleiken** [comment]
@susanSanjhya The survey response is collected in a webview via surveymonkey.com -- the error codes mentioned above are all SDK error codes and the SDK is only invoked either after the response has been collected OR the user canceled out of the survey. That means that errors 2 and 10 only pertain to the SDK -- which attempts to fetch the user's survey response from our servers. 
 Those errors only indicate that that fetch failed -- not that the user's submission failed necessarily.

**Comment by susanSanjhya** [comment]
@benleiken 
Thank you for your kind information. I will consider above cases.
