### ISSUE TITLE
Handling surveys

### ISSUE THREAD

**Issue by apurvpandey** [SurveyMonkey/surveymonkey-android-sdk#34]
@benleiken 
I am integrating Survey Monkey into my Android app. You doc is really helpful. Though, I have certain use cases and would like some help: 

- Show a particular survey to my users particular no. of times.  (lets say 3). If they still don't feel like filling the survey, don't show it next time. 
- If user has responded to a particular survey, don't show it to them next time.
- Maintain above scenarios even if user has cleared shared preference for their app.
- Displaying survey to user once each day.

Can I handle all these using Survey Monkey dashboard? If not, then how to handle above scenarios?

**Comment by benleiken** [comment]
@apurvpandey -- glad the docs are helpful!

The two scenarios you mentioned as well as your fourth bullet point can all be handled, but you'd need to implement code to handle them. Our SDK doesn't handle any of those cases by default. 

As far as maintaining the behavior even if the user clears their shared prefs. -- that would again be up to you to implement. All we can offer are suggestions.

If you're successful in implementing any/all of those scenarios, please do feel free to open a PR into our documentation -- we'd appreciate that very much.
