### ISSUE TITLE
Softkeyboard hides focused input

### ISSUE THREAD

**Issue by adamdye** [SurveyMonkey/surveymonkey-android-sdk#35]
The last question in my survey in a text input.  Once I click it, the softkeyboard is displayed.  The WebView resizes, but it doesn't not scroll its content to bring the focused input back into view.  Can you please modify the WebView to adjust its scroll position on resize?

**Comment by benleiken** [comment]
@adamdye unfortunately this is a limitation of android webviews that we've encountered before. there doesn't appear to be a fix as we don't have control of the focusing behavior of the webview. if you have any specific suggestions, we're all ears and would appreciate them very much!
