### ISSUE TITLE
Crash when launching the survey 

### ISSUE THREAD

**Issue by ldimitroff** [SurveyMonkey/surveymonkey-android-sdk#36]
Caused by: java.lang.IllegalArgumentException: Receiver not registered: null

Seems that a hash that has changed or disabled, I'm getting this crash in the app.

**Comment by ldimitroff** [comment]
By debugging I found that you're using the SMFeedbackActivity onCreate with SMFeedbackFragment even if the error has been given as result: 

> @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Intent intent = getIntent();
        mSPageHTML = intent.getStringExtra(KEY_SM_SPAGE_HTML);
        if (mSPageHTML == null) {
            mError = SMError.sdkClientErrorFromCode(SMError.ErrorType.ERROR_CODE_COLLECTOR_CLOSED, null);
            Log.d(SMConstants.DEBUG_TAG, mError.getDescription());
            onFetchRespondentFailure(mError);
        }
        mURL = intent.getStringExtra(KEY_SM_SPAGE_URL);
        if (savedInstanceState == null) {
            getSupportFragmentManager().beginTransaction().add(android.R.id.content, SMFeedbackFragment.newInstance(mURL, mSPageHTML, true), SMFeedbackFragment.TAG).commit();
        }

and with this on SMFeedbackFragment created, calls the destroy automatically without creating the view...

> @Override
    public void onDestroy() {
        getActivity().unregisterReceiver(connectivityMonitor);
        super.onDestroy();
    }

Either put the else if (savedInstanceState == null) , cause it's one or another, or check connectivityMonitor != null

**Comment by SimonSchubert** [comment]
Same problem here. @ldimitroff What did you end up doing? @benleiken

**Comment by benleiken** [comment]
@ldimitroff @SimonSchubert Thanks for writing in -- we're actively working on a new version of the SDK with this issue (and others) fixed. We should have something out within 2-3 weeks at most. I'll post here as soon as it's available.

**Comment by SimonSchubert** [comment]
@benleiken Thank you for the feedback. I'm looking forward for the new version.

**Comment by ayeung** [comment]
@ldimitroff Thanks for reporting this.  I added a null check for connectivityMonitor as you suggested, so it should be fixed in the next version of the sdk.  Please let us know if it continues to be an issue.
