### ISSUE TITLE
SMFeedbackFragment cannot submit a survey more than once per activity instance

### ISSUE THREAD

**Issue by jbir789** [SurveyMonkey/surveymonkey-android-sdk#38]
There is a flaw in the implementation of `SMFeedbackFragment` that prevents the Fragment from sending a survey result more than once per activity instance (the app will freeze if the user does so). Here are two bugs we found in the Fragment implementation by looking at the source:
 * `SMFeedbackFragment#getToken`: This method is broken because its first line use the wrong loader id. In fact, `getActivity().getSupportLoaderManager().getLoader(2)` returns a `GetRespondentTaskLoader` and not a `GetRespondentTokenTaskLoader`. Initially, this will work. But if the user attempts to submit another survey, it will crash because of a class cast exception. The fix is straightforward since the line can just be replaced by:
```java
GetRespondentTokenTaskLoader loader = (GetRespondentTokenTaskLoader) getActivity().getSupportLoaderManager().getLoader(RESPONDENT_TOKEN_LOADER_KEY);
```
 * Now, there is another issue in `SMFeedbackFragment#getToken` and `SMFeedbackFragment#onGetRespondentTokenTaskLoadFinished`: `initLoader` and `restartLoader` are both called if the loader is not null. If you take a look at their doc, both methods will start a loader. So the second time a user send a survey, the loader will execute twice, resulting in both the error and success callback being called in a row. The fix is to simply remove `initLoader`, since it is not required. (`restartLoader` will also init the loader, if it doesn't exist)

These issues are a blocker for our app. Can you please provide a new version of the SDK including this fix?

**Comment by benleiken** [comment]
@jbir789 thanks for reporting -- we'll have a fix out for this issue as soon as we can -- within a couple of weeks. please bear with us.

**Comment by ayeung** [comment]
@jbir789 I removed init loader as you suggested.  As a result, getting the loader was unnecessary and removed as well.  Thanks for bringing this up.  It should be in the next release, so please let us know if you are still running into this issue.  Thanks!
