### ISSUE TITLE
Too many field references to fit in one dex file

### ISSUE THREAD

**Issue by mrobitaille-sem** [SurveyMonkey/surveymonkey-android-sdk#43]
I am having the dex limit error (https://developer.android.com/studio/build/multidex.html) when I integrate the SDK. It comes from the dependency com.android.support.appcompat-v7. Could you validate that this dependency is needed and use the most restrictive dependency possible. I cannot use the multidex solution because of our build pipeline.

**Comment by ayeung** [comment]
We are currently using it for the support fragment class, so I don't think we can remove it.
