### ISSUE TITLE
No progress indicator during network call

### ISSUE THREAD

**Issue by emilmarkose** [SurveyMonkey/surveymonkey-android-sdk#44]
In this method `SurveyMonkey#startSMFeedbackActivityForResult(...)` there is a network call ongoing. But there is no progress indicator showing.
Please show a progress indicator during this task. Otherwise user thinks that its broken and might cancel the operation.
Also after the survey is completed when we click on the "DONE" button same behavior exists. Please fix that also.

Best Regards
Emil Markose

**Comment by Reyske** [comment]
As we are targeting mainly older people with our app, they don't have a clue what is going on.
They just keep tapping the next button because there is no indication at all that something is loading.

A fix would be highly appreciated.

**Comment by ayeung** [comment]
There is already a progress indicator when you initially launch the feedback fragment (called by startSMFeedbackActivityForResult).  I changed the behavior to start showing when the view is visible, maybe that will help.  I also added a progress indicator when tapping next/done buttons.  This will be out on the next release: 1.0.7

**Comment by ayeung** [comment]
Just released 2.0.0.  Check it out when you get the chance.  I'll be closing this issue for now, feel free to reopen and/or comment if you are still having issues.

Note that I did run into a situation where the previous version of the library was cached on Android Studio, so I would also invalidate the cache to make sure you are grabbing the latest if you run into any issues.
