### ISSUE TITLE
How to get respondent data returned by SDK when presenting surveys from fragment

### ISSUE THREAD

**Issue by pradnyadikleVRL** [SurveyMonkey/surveymonkey-android-sdk#45]
I am presenting survey from fragment, I would need to use data returned from sdk.

1.  I tried to override onActivityResult in fragment from where I have presented survey but couldn't get anything here
2. I am also overriding parent activity's onActivityResult method.

Can you guys help on this?

**Comment by JoelSalzesson** [comment]
SMFeedbackFragmentListener

**Comment by ayeung** [comment]
I would make sure your activity implements SMFeedbackFragmentListener as Joel mentioned.  You can use the example as a reference:

https://github.com/SurveyMonkey/surveymonkey-android-sdk/blob/master/SimpleSurvey/app/src/main/java/com/surveymonkey/simplesurvey/SimpleFragmentActivity.java#L50
