### ISSUE TITLE
NullPointerException on SMFeedbackFragment.getToken

### ISSUE THREAD

**Issue by TopeMateo** [SurveyMonkey/surveymonkey-android-sdk#47]
Hello, I've experienced one crash from an android device  (Samsung A8, Android 6.0.1) saying:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.support.v4.app.LoaderManager android.support.v4.app.FragmentActivity.getSupportLoaderManager()' on a null object reference

com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.getToken (SMFeedbackFragment.java:241)
--
  | com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.access$500 (SMFeedbackFragment.java:35)
  | com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$SMWebviewClient.onPageStarted (SMFeedbackFragment.java:272)
  | com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted (WebViewContentsClientAdapter.java:229)
  | org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage (AwContentsClientCallbackHelper.java:20)
  | android.os.Handler.dispatchMessage (Handler.java:102)
  | android.os.Looper.loop (Looper.java:148)
  | android.app.ActivityThread.main (ActivityThread.java:7325)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

I'm using 1.0.6 android sdk version.

Do you guys know what's wrong?

**Comment by ayeung** [comment]
Not sure how that case happened, but it sounds like the activity that you used to launch the fragment was destroyed.  Maybe you happen to have that android setting: Settings -> Developer Options -> Don't keep Activities enabled?  In any case, I added some checks for it to fail gracefully in those cases when it happens as opposed to crashing.  Should be in the next release 1.0.07

**Comment by TopeMateo** [comment]
@ayeung looking forward to the update!!

**Comment by ayeung** [comment]
Just released 2.0.0.  Check it out when you get the chance.  I'll be closing this issue for now, feel free to reopen and/or comment if you are still having issues.

Note that I did run into a situation where the previous version of the library was cached on Android Studio, so I would also invalidate the cache to make sure you are grabbing the latest if you run into any issues.
