### ISSUE TITLE
open survey page really slow!

### ISSUE THREAD

**Issue by Fortiskrito** [SurveyMonkey/surveymonkey-android-sdk#5]
when i click a button, I use `sdkInstance.startSMFeedbackActivityForResult(this, [SAMPLE_REQUEST_CODE], [SAMPLE_SURVEY_HASH]);` to start survey page. but the loading time is so long that user will not bear. user will wait a long time( about 1~2s) to see the loading icon of survey and will wait almost the same time to load survey.
is this problem caused by internet? I tested it in China, is there some solutions?

**Comment by benleiken** [comment]
@Fortiskrito Unfortunately this problem is indeed caused by the internet connection -- we don't currently have in-country hosting in China and this contributes to the latency -- I'll update/reopen this if anything changes.

**Comment by teeleek** [comment]
9

**Comment by teeleek** [comment]
100.00.t.l
