### ISSUE TITLE
 when we tap on Submit button two or more times our App crashes

### ISSUE THREAD

**Issue by alexjheu** [SurveyMonkey/surveymonkey-android-sdk#54]
We are seeing crashes when we tap on Submit button two or more times

NOTE: we have the Survey Monkey SDK into our Android App

Steps:

Fill in the survey everything
tap on Submit 2 or more times
App Crashes

**Comment by alexjheu** [comment]
@ayeung  any update?

**Comment by ayeung** [comment]
I tried to reproduce a while ago, and did not have any luck.  I tapped submit multiple times and it still went through fine.  Logs, device info and any other information would be helpful

**Comment by alexjheu** [comment]
@ayeung Would we be able to schedule a call so we can show you the crash?

**Comment by ayeung** [comment]
@alexjheu Would you mind trying to reproduce on the sample app in this repo?  I tried running it on that app, and it worked for me.

**Comment by alexjheu** [comment]
What sample app?

**Comment by ayeung** [comment]
This repo: surveymonkey-android-sdk has a sample app in it called SimpleSurvey, you just need to import this project and run it

**Comment by alexjheu** [comment]
we can close this issue. My team closed this internally.

**Comment by alexjheu** [comment]
@ayeung we are still able to reproduce on our end

**Comment by ayeung** [comment]
I've tried this on a Galaxy S7 in the sample app with no luck. The crash log would also be helpful.

**Comment by ayeung** [comment]
This is a duplicate of https://github.com/SurveyMonkey/surveymonkey-android-sdk/issues/38 and is already fixed in the latest version of the sdk
