### ISSUE TITLE
Does the method "onFetchRespondentFailure", also return error when there is timeout in form submission

### ISSUE THREAD

**Issue by nitika-bhatia** [SurveyMonkey/surveymonkey-android-sdk#58]
The method does get triggered when a user taps the cancel button or submits the form finally(only if there is error). Does the  method also get triggered when there is a timeout on the final form submission?

Also, what is the policy with the request's timeout in the SDK. How much is it, in terms of seconds?

If the method is not triggered, on timeout, then are there any other way(s) of knowing/handling it?

Also, is there a way to reproduce and test this scenario or in other words how possible is it for this situation to occur?

PS: here, timeout on final submission means that the user taps the submit button on the final page and the SDK transfers the response to SM. If this process takes longer than a certain number of seconds then it should timeout, to avoid the user to keep waiting.

**Comment by ayeung** [comment]
onFetchRespondentFailure only gets called when we submit the form (when the user is done with the survey).

The current timeout is 15s connect and 10s read.  We didn't call onFetchRespondentFailure on timeout failures before, but I have added this in the next release 1.0.7

**Comment by ayeung** [comment]
Just released 2.0.0.  Check it out when you get the chance.  I'll be closing this issue for now, feel free to reopen and/or comment if you are still having issues.

Note that I did run into a situation where the previous version of the library was cached on Android Studio, so I would also invalidate the cache to make sure you are grabbing the latest if you run into any issues.
