### ISSUE TITLE
Application Freezes leaving the survey screen

### ISSUE THREAD

**Issue by tek292** [SurveyMonkey/surveymonkey-android-sdk#6]
I implemented the sdk in my application. I fire survey on a button click. When I leave the survey screen (either by answering or hitting the back button), the survey screen closes and the application locks up. It doesn't matter what screen I launch the survey from. I am not overriding onActivityResult, but I know it does get fired from when I was trying to determine the cause of the freeze. Logcat does not generate anything.

**Comment by benleiken** [comment]
@tek292 This is fixed now, thanks for pointing it out!
