### ISSUE TITLE
mashery_api and respondent_token showing when finishing a survey

### ISSUE THREAD

**Issue by roni-castro** [SurveyMonkey/surveymonkey-android-sdk#63]
When I click DONE button, finishiong a survey, it is showing the mashery_api_key and respondend_token before closing the view. What are these values? Is it save to show it to the user? How to not show it?
The android device is Moto X Play 6.0.1
I am using version SDK 1.0.6, as I cannot increase my minimum SDK to 21 that version 2.0.0 requires.

![screenshot_20190123-175630](https://user-images.githubusercontent.com/24610813/51633795-a696ac00-1f39-11e9-80e1-2d0438b78401.png)

I am doing this when showing a survey:

```
    SurveyMonkey surveyMonkeyInstance = new SurveyMonkey();
    if(getActivity() != null) {
      surveyMonkeyInstance.startSMFeedbackActivityForResult(getActivity(), SURVEY_MONKEY_REQUEST, SURVEY_MONKEY_KEY_SURVEY_COLLECTION_KEY);
    }
  }
```

**Comment by roni-castro** [comment]
Duplicate of #62

**Comment by paullharper** [comment]
I am using version 2.0 and still getting the same problems.
