### ISSUE TITLE
SDK Minimum version is 21

### ISSUE THREAD

**Issue by roni-castro** [SurveyMonkey/surveymonkey-android-sdk#64]
My minimum sdk version 19 and I can't increase to 21.
Why do the release 2.0.0 have the **minSdkVersion 21**?

It is giving me error when compiling:
`> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.surveymonkey:surveymonkey-android-sdk:2.0.0] `

**Comment by ayeung** [comment]
Sorry, for security reasons, we no longer support versions below 21

**Comment by jisung** [comment]
This is a disappointing decision. our app is a finance app and the min sdk is 19 though. A library should support lower min-sdk than the customer apps unless you intend to lose your customers.

**Comment by gnuhel** [comment]
I also want to ask you to decrease min SDK to 19. Our app still needs to support android 19. In version 1 there is a bug where it shows JSON after ending the survey.
