### ISSUE TITLE
onActivityResult is not a Success

### ISSUE THREAD

**Issue by tek292** [SurveyMonkey/surveymonkey-android-sdk#7]
Hello again.

Yesterday, I upgraded my SurveyMonkey Account to the **Select** plan to so I may have unlimited responses. I created a new survey today and implemented it in my application. While attempting to parse a success result survey, my success logic is never fired. Instead, I consistently receive the following error:

**Domain: SurveyMonkeySDK_ServerError Code: 7 SMDescription: Response limit exceeded for your plan. Upgrade to access more responses through the SDK.**

While the survey I am testing does have question skip logic, even when I go through the entire survey I get this error.

**Comment by benleiken** [comment]
@tek292 The feature you're trying to use (i.e. parsing the response in real-time) is for Gold plans and higher, which is why you're getting that error. I will update the docs to make this more clear!

**Comment by ammacdonald1** [comment]
I got the same error and after reading that 'Response limit exceeded for your plan' I thought that it meant I hit the response limit for the plan I was on so I too upgraded to Select only to find that the error persisted- and read this to find out it has nothing to do with the response limit...

I would think a paid account should at least let me get a callback from the SDK telling me whether the user cancelled out of the survey or submitted it- which is the only thing I'm looking for right now.

**Comment by benleiken** [comment]
@ammacdonald1 I apologize for the confusion. The next update of the SDK will have a more specific error message.

I'll pass your feedback re: SELECT plans including response data on to our plans and packaging team, but right now this functionality is only enabled for GOLD and PLATINUM plans.
