### ISSUE TITLE
Standard subscription erroring out

### ISSUE THREAD

**Issue by a-koka** [SurveyMonkey/surveymonkey-android-sdk#74]
I'm using a survey tied to a paid account with standard subscription. SurveyMonkey support center says this is an SDK issue as my account should not throw any errors.

Look at the code and error below. This survey has nowhere near 1000 responses, I was testing with a brand new survey.

![code](https://user-images.githubusercontent.com/16167317/63901628-38780300-c9ba-11e9-90a0-04f55f2814f4.png)
![error](https://user-images.githubusercontent.com/16167317/63901632-3a41c680-c9ba-11e9-912e-4fdb356e6796.png)

**Comment by ayeung** [comment]
Believe support center resolved this.  You need to have ADVANTAGE or higher to be able to route flows based off of user responses.  The snippet from the FAQ mentions this:

```How can I route my app users to different flows based on their survey response?

If you have a ADVANTAGE plan or higher, you can program your app to route your users into different flows based on their responses to your survey. For example, if a user responds to your in-app feedback survey and gives your app a 5-star rating, your app could take that user down the "5-Star Rating Flow" into the app store to rate your app. You could also take a user down the "Needs Improvement Flow" to the help center in your app.```
