### ISSUE TITLE
Open Collector still responds with Error Code: 4 "The collector for this survey has been closed." 

### ISSUE THREAD

**Issue by producerism** [SurveyMonkey/surveymonkey-android-sdk#77]
I have triple checked the survey hash, and also to verify the collector is active, which it is. I see this on the collector screen for this particular collector:
![image](https://user-images.githubusercontent.com/281948/64451292-e0c05280-d0b1-11e9-8fa2-684a19a7f991.png)

However logs show this when using `SimpleFragmentActivity.startActivity` from example:
> D/SM_SDK_DEBUG: Domain: SurveyMonkeySDK_ServerError Code: 4 SMDescription: The collector for this survey has been closed.

And show this when using `startSMFeedbackActivityForResult`
> D/SM_SDK_DEBUG: Domain: SurveyMonkeySDK_ServerError Code: 4 SMDescription: 

(same error, just no description given).

Happy to provide more feedback, though the implementation is the same as the example on github, only in kotlin.

**Comment by ayeung** [comment]
This seems like an account specific issue, please reach out to our api support at api-support@surveymonkey.com and they can debug it on your account with you

**Comment by producerism** [comment]
@ayeung thanks, will close this ticket and contact support then.
