### ISSUE TITLE
How to include MemberID information in mobileSDK distribution

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-android-sdk#79]
Hello everyone, I am having trouble to include MemberID (push from our app, can't be edited & can't be seen by members) for a survey within my app. I have tried adding custom variables, but the response does not include the custom variable fields. Can anyone help me with this issue? Thank you

**Comment by ayeung** [comment]
Sorry, the SDK does not currently support this functionality.  We don't support the ability to pass information from the app to the survey
