### ISSUE TITLE
App not responding when cancel or submit the survey

### ISSUE THREAD

**Issue by Govindakarthikeyan** [SurveyMonkey/surveymonkey-android-sdk#8]
Hello,

App was not responding at the following scenario,

Once I submit the survey or cancel the survey, My app getting frozen, so that I couldn't able to proceed the App further. Later I am getting the alert as "App not responding".

I am attaching the screenshots herewith.

Note: Currently I am using latest source code (please refer this link https://github.com/SurveyMonkey/surveymonkey-android-sdk/releases/tag/1.0.3)

Kindly do the needful on this issue.
![screenshot_2016-03-31-17-00-40-40](https://cloud.githubusercontent.com/assets/14067737/14174927/5f123d1c-f765-11e5-9a40-8c04e0fa6b75.png)
![screenshot_2016-03-31-17-05-33-40](https://cloud.githubusercontent.com/assets/14067737/14174928/5f18797a-f765-11e5-8687-cf79a36cba96.png)

**Comment by benleiken** [comment]
@Govindakarthikeyan This issue should be fixed in that release. Can you delete the SDK from your project and install using [jCenter](https://github.com/SurveyMonkey/surveymonkey-android-sdk#step-1-download-mobile-sdk)? Let me know if that fixes things

**Comment by Govindakarthikeyan** [comment]
Thanks benleiken for the solution. I tried installing using jCenter. Finally, it worked out & fixed the issue

**Comment by benleiken** [comment]
@Govindakarthikeyan glad to hear that, don't hesitate to let me know if other issues pop up. Thanks for using the sdk!
