### ISSUE TITLE
Does SurveyMonkey has a specific API to avoid duplicated submission using custom variables?

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-android-sdk#80]
I am trying to avoid duplicated submission using customvariables. 
Does SurveyMonkey has a specific API to avoid duplicated submission using custom variables? 

Thank you

**Comment by ayeung** [comment]
Custom variables were not designed to create unique survey responses, so there is no way to avoid duplicate submission there.  Since it sounds like you track them with some member ID, it might be best if your app tracked whether the user has submitted a response or not.
