### ISSUE TITLE
How to reduce load time after pressing the SurveyMonkey SDK through my app?

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-android-sdk#81]
Hi Survey Monkey,
I recently try SurveyMonkey Mobile SDK and experiencing this issue

mobile SDK is taking a really long time during these events:
1. is when you press the survey button in my app and it takes time to go to loader.
2. The loader itself

I googled about loader time, and I kinda fixed it by cutting my questions into pages, but still cant solve number one. 
I am afraid that, customer using my app might think it is unresponsive and keep clicking the button which will result in opening same survey page multiple times.

Any ways to help fixing this?

Thank you.

**Comment by ayeung** [comment]
I'm not sure what's causing the delay, possibly an older device or network issue?

The survey just loads in a webview, so there isn't much we can do to improve the performance.  If you're afraid the customer can open multiple surveys, I would recommend you programmatically prevent the user from doing so via a flag or something.
