### ISSUE TITLE
Why android mobile SDK does not work on Nokia5?

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-android-sdk#82]
Hello SurveyMonkey,

after applying surveymonkey SDK into my app, it works perfectly in my android, but it just would not open in Nokia5, do you have any device restriction? or anything workaround for specific devices?

Please kindly help with this issue. Thank you

**Comment by ayeung** [comment]
I only restriction we have is:

`As of version 2.0.0, the minsdk for this library is Api 21 (Android 5.x)`
