### ISSUE TITLE
Survey App

### ISSUE THREAD

**Issue by spudatron** [SurveyMonkey/surveymonkey-android-sdk#84]
Is it possible to use the SDK to create a survey app for internal staff? So any new surveys created can appear in the app and the staff can be notified to go to the app to take the survey.

From the description my understanding is that the SDK is more design for a single survey in relation to a specific app and each time you want to run a survey you'd have to do a new app release.

**Comment by ayeung-sm** [comment]
It was designed for a single survey use, but you could probably work around it by having the server return the survey hash to launch a survey of your choice at runtime.  In terms of getting a notification to take the survey, that work would be done inside your app before launching the survey taking experience.

**Comment by spudatron** [comment]
Thats what I was thinking might have to be done. Cheers for the responses.
