### ISSUE TITLE
Event triggered survey should no longer display

### ISSUE THREAD

**Issue by cartercasner** [SurveyMonkey/surveymonkey-android-sdk#9]
I have followed documentation and set up the sdk so that is triggers a survey after a user completes a certain event in the app. I am wondering what the sdk does if the survey collector is closed and a user completes this event?

**Comment by benleiken** [comment]
@cartercasner If the collector is closed, the survey is not presented and an error is returned by the SDK.

**Comment by cartercasner** [comment]
Thanks for the response Ben, is there anyway to keep an error from returning to the user?

**Comment by benleiken** [comment]
@cartercasner The error won't be displayed to the user -- they just won't see a survey. The error is returned for your app to handle as you wish.
